name: fetch-misskey

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: clone
        working-directory: ./fetch/misskey
        run: |
          rm -rf ./{*,.*}
          git init
          git config core.sparsecheckout true
          git remote add origin https://github.com/misskey-dev/misskey.git
          cp ../../files-misskey ./.git/info/sparse-checkout
          git pull origin develop
          rm -rf .git

      - name: Branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: pr
        run: |
          git config --global user.email "none"
          git config --global user.name "bot"
          git switch -c fetch
          git add src
          git commit -m'fetch misskey'
          git push -u origin fetch

      - name: Create Pull Request
        continue-on-error: true
        run: |
          gh pr create --fill -B "${GIT_BRANCH_NAME}"
